# General settings
name: "graph-tf-model" # Warning: 'debug' and 'test' are reserved name that have a special behavior
prepend_date_in_name: true # Prepend date in front of general.name

wandb: "online" # online | offline | disabled
project_name: DDSBM_${dataset.name} # wandb project name

gpus: 1 # Multi-gpu is not implemented on this branch

resume: null # If resume, path to ckpt file from outputs directory in main directory
test_only: null # Use absolute path

save_every_n_epochs: 50
check_val_every_n_epochs: 10
sample_every_val: 25
val_check_interval: null
samples_to_generate: 10000 # We advise to set it to 2 x batch_size maximum
samples_to_save: 0
chains_to_save: 8
log_every_steps: 50
sample_batch_size: 1000
number_chain_steps: 30 # Number of frames in each gif

final_model_samples_to_generate: 10000
final_model_samples_to_save: 30
final_model_chains_to_save: 20

evaluate_all_checkpoints: false
seed: 42
