# Optionally, you can specify a 'fail_fast' flag to stop on the first error:
# fail_fast: true
default_language_version:
  python: python3
  node: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: .*\.pdb
      - id: end-of-file-fixer
        exclude: .*\.pdb
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
        name: "ruff lint"
        exclude: "^esm/"
      - id: ruff-format
        name: "ruff format"
        types_or: [python, pyi, jupyter]
        exclude: "^esm/"

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types: [yaml]
        exclude: "environment.yaml"
