name: zinc # should be set manually
datadir: data/${dataset.name}
datadirname: ${general.name}
original_datadirname: ZINC250k_logp_2_4_random_matched_no_nH
pin_memory: false
remove_h: true
compute_dataset_infos: false
unconditional: false
