name: uncond_qm9 # should be set manually
datadir: data/${dataset.name}
datadirname: ${general.name}
original_datadirname: qm9
pin_memory: false
remove_h: true
compute_dataset_infos: false
unconditional: true
prior_sample: true
