name: uncond_comm20 # should be set manually
datadir: data/${dataset.name}
datadirname: ${general.name}
original_datadirname: comm20
pin_memory: false
remove_h: false
compute_dataset_infos: false
unconditional: true
prior_sample: true
